name: Extract envoy.exe
on: push

jobs:
  extract:
    name: Extract envoy.exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract envoy.exe
        shell: pwsh
        run: ./extract-envoy.ps1

      - uses: actions/upload-artifact@v3
        with:
          name: envoy
          path: envoy.exe